#!/bin/sh

## Quand le script est exécuté au démarrage, la variable $PATH est encore vide.
gpio="/usr/local/bin/gpio"
raspistill="/usr/bin/raspistill"
raspivid="/usr/bin/raspivid"
convert="/usr/bin/convert"

## Définition des pins
detect=1
oiseau_entree=5
oiseau_sortie=4

## Définition du mode des pins
$gpio mode $detect in
$gpio mode $oiseau_entree out
$gpio mode $oiseau_sortie out

## Variables globales
oiseau_dedans=0

## Programme
while true
do
	la_date=`date "+%Y-%m-%d_%H-%M-%S-%2N"`

	# On attend 500 ms pour ne pas surcharger la Raspberry <3
	sleep .5

	# On test si on a une tension de sortie sur le détecteur de mouvement
	if [ `$gpio read $detect` -eq 1 ]
	then
		# On vérifie si l'oiseau est déjà dans la cage
		if [ $oiseau_dedans -eq 0 ]
		then
			oiseau_dedans=1
		else
			oiseau_dedans=0
		fi

		# On allume une led en fonction de la position de l'oiseau
		if [ $oiseau_dedans -eq 1 ]
		then
			$gpio write $oiseau_entree 1

			echo "[$la_date] Omg un oisal vient d'entrer !!!"

			# Cut le stream comme un porc
			kill -9 `ps ax | grep $raspivid | tr -d '[:space:]' | grep -Eo '[0-9]*' | head -n 1`

			# Un oiseau est rentré, on prend une photo :d
			$raspistill -t 1 -o "public/pics/"$la_date".jpg"

			# Création de la miniature
			$convert "public/pics/"$la_date".jpg" -gravity Center -thumbnail 300x200^ "public/pics/"$la_date"_thumbnail.jpg"

			# On relance le stream
			./stream&
		else
			$gpio write $oiseau_sortie 1
			echo "[$la_date] Omg l'oisal est sorti !!"
		fi

		# On attend que le détecteur de mouvement ne détecte plus rien
		while [ `$gpio read $detect` -eq 1 ]
		do
			echo "[$la_date] ..."
			sleep .2
		done

		# Reset
		$gpio write $oiseau_sortie 0
		$gpio write $oiseau_entree 0

	else
		echo "[$la_date] Aucun oiseau n'est passé par ici"
	fi
done
