#!/bin/sh

## Quand le script est exécuté au démarrage, la variable $PATH est encore vide.
raspivid="/usr/bin/raspivid"
ffmpeg="/usr/local/bin/ffmpeg"

$raspivid -t 0 -p "0,0,0,0" -h 720 -w 1280 -fps 25 -b 500000 -vf -o - | $ffmpeg -i - -vcodec copy -an -f flv -metadata streamName=myStream tcp://0.0.0.0:6666

